title: The Accidental Entrepreneur
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2741936
  brandStrength: 0.3125
  lightness: 0.3781362
  brandColors:
    - '#ffffff'
    - '#00548b'
    - '#000000'
    - '#666666'
    - '#c5c5c5'
  rhythmicContrast: 0.6075269
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: getner
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.41301
layout_spectrum: 0.2383513
