name: getner
favicon: null
layout_spectrum: 0
typography_spectrum: 0.41301
title: The Accidental Entrepreneur
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00548b'
    - '#000000'
    - '#666666'
    - '#c5c5c5'
  brandStrength: 0.3125
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.45958064240403473
purpose: []
